# Docker Compose Override File
# This file overrides the default port mappings in docker-compose.yml
# Place this file in the same directory as docker-compose.yml

services:
  backend:
    ports:
      - "3032:8000"  # Map host port 3032 to container port 8000

  frontend:
    ports:
      - "8082:80"    # Map host port 8082 to container port 80