# Production-specific overrides
services:
  backend:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - APP_ENV=production
      - DEBUG=false
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
    labels:
      - "com.repovista.service=backend"
      - "com.repovista.environment=production"

  frontend:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    labels:
      - "com.repovista.service=frontend"
      - "com.repovista.environment=production"

# Production volumes use default local driver
# To use bind mounts, directories must exist and have proper permissions
volumes:
  backend-logs:
    driver: local
  
  nginx-logs:
    driver: local